name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh $SSH_USERNAME@$EC2_HOST 'bash -s' << 'ENDSSH'
            # Update package list
            sudo apt-get update

            # Install Node.js and npm
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Verify installations
            node --version
            npm --version

            # Install PM2 globally
            sudo npm install -g pm2

            # Navigate to project directory (create if doesn't exist)
            mkdir -p ~/stripe-backend
            cd ~/stripe-backend

            # Pull latest changes
            git pull origin main || git clone https://github.com/umer-waltz/stripe-backend.git .

            # Install dependencies
            npm install

            # Set up environment variables
            echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" > .env
            echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env

            # Restart PM2 process (create if doesn't exist)
            pm2 restart stripe-backend || pm2 start server.js --name stripe-backend
          ENDSSH